require_relative "combo/base"
require_relative "combo/single"
require_relative "combo/vertical"
require_relative "combo/diagonal"
require_relative "combo/calendar"
require_relative "combo/spread_roll"
